jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 9090
   servlet:
      context-path: /reservacionHotel
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:postgresql://localhost:5432/ReservasHotel
      username: postgres
      password: angela
      hikari:
         poolName: pool
